import { useState } from 'react';
import { RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { Page } from '@/components/layout/Page';
import { Button } from '@/components/ui/Button';
import { EmptyState, ErrorState, Panel, Skeleton } from '@/components/ui/States';
import { fmt, humanError } from '@/lib/utils';
import { useAdminUsers } from '@/features/admin/api';
import { Pager, SearchToolbar } from '@/features/admin/AdminComponents';

const PAGE_SIZE=25;
export default function AdminUtilizadores(){
  const [search,setSearch]=useState(''); const [applied,setApplied]=useState(''); const [offset,setOffset]=useState(0);
  const q=useAdminUsers({search:applied,limit:PAGE_SIZE,offset}); const total=q.data?.[0]?.total_count??0;
  return <Page title="Utilizadores" subtitle={total+' utilizador'+(Number(total)===1?'':'es')} actions={<Button variant="secondary" size="sm" onClick={()=>void q.refetch()} disabled={q.isFetching}><RefreshCw size={14} className={q.isFetching?'animate-spin':''}/>Actualizar</Button>}>
    <SearchToolbar><div className="relative flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-lo"/><input className="field pl-9 w-full" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){setOffset(0);setApplied(search.trim())}}} placeholder="Nome, email ou telefone" aria-label="Pesquisar utilizadores"/></div><Button size="sm" onClick={()=>{setOffset(0);setApplied(search.trim())}}><Search size={14}/>Pesquisar</Button></SearchToolbar>
    {q.isLoading?<Skeleton className="h-72" lines={7}/>:q.error?<ErrorState message={humanError(q.error)} onRetry={()=>void q.refetch()}/>:q.data?.length===0?<EmptyState title="Nenhum utilizador encontrado." body="Ajuste a pesquisa e tente novamente."/>:<Panel className="p-0 overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b border-white/10 t-label text-ink-lo text-left"><th className="px-5 py-3">Utilizador</th><th className="px-5 py-3">Estado</th><th className="px-5 py-3">Acesso</th><th className="px-5 py-3">Barbearias</th><th className="px-5 py-3">Registo</th><th className="px-5 py-3">Último acesso</th></tr></thead><tbody>{q.data.map(u=><tr key={u.id} className="border-b border-white/5 last:border-0"><td className="px-5 py-4"><p className="text-ink-hi">{u.full_name||'Sem nome'}</p><p className="t-label text-ink-lo mt-0.5">{u.email}</p>{u.phone&&<p className="t-label text-ink-lo">{u.phone}</p>}</td><td className="px-5 py-4"><span className={'inline-flex rounded-full border px-2.5 py-1 t-label '+(u.is_confirmed?'text-st-completed border-st-completed/30':'text-ink-mid border-white/10')}>{u.is_confirmed?'Confirmado':'Por confirmar'}</span></td><td className="px-5 py-4">{u.is_platform_admin?<span className="inline-flex items-center gap-1.5 rounded-full bg-accent-soft px-2.5 py-1 t-label text-accent-ink"><ShieldCheck size={13}/>Admin Oryon</span>:<span className="t-label text-ink-mid">Utilizador</span>}</td><td className="px-5 py-4">{u.shop_count}<div className="flex flex-wrap gap-1 mt-1">{Array.isArray(u.shop_roles)&&u.shop_roles.slice(0,3).map((r:any)=><span key={String(r.shop_id)} className="t-label text-ink-lo">{r.shop_name+' · '+r.role}</span>)}</div></td><td className="px-5 py-4 text-ink-mid">{fmt(u.created_at,'dd MMM yyyy')}</td><td className="px-5 py-4 text-ink-mid">{u.last_sign_in_at?fmt(u.last_sign_in_at,'dd MMM yyyy, HH:mm'):'Nunca'}</td></tr>)}</tbody></table></div></Panel>}
    {!q.isLoading&&!q.error&&<Pager offset={offset} pageSize={PAGE_SIZE} total={Number(total)} onPrev={()=>setOffset(Math.max(0,offset-PAGE_SIZE))} onNext={()=>setOffset(offset+PAGE_SIZE)}/>}
  </Page>
}