import { useState } from 'react';
import { Plus, RefreshCw, Search } from 'lucide-react';
import { Page } from '@/components/layout/Page';
import { Button } from '@/components/ui/Button';
import { EmptyState, ErrorState, Panel, Skeleton } from '@/components/ui/States';
import { fmt, humanError } from '@/lib/utils';
import { useAdminShops, useAdminSupport, useAdminUsers, useCreateAdminSupport, useUpdateAdminSupport, type SupportPriority, type SupportStatus } from '@/features/admin/api';
import { AdminStatus, Pager, SearchToolbar } from '@/features/admin/AdminComponents';

const PAGE_SIZE=25;
export default function AdminSuporte(){
  const [search,setSearch]=useState('');const [applied,setApplied]=useState('');const [status,setStatus]=useState<SupportStatus|null>(null);const [priority,setPriority]=useState<SupportPriority|null>(null);const [offset,setOffset]=useState(0);
  const q=useAdminSupport({search:applied,status,priority,limit:PAGE_SIZE,offset});
  const shops=useAdminShops({search:'',status:null,limit:100,offset:0});
  const admins=useAdminUsers({search:'',limit:100,offset:0});
  const create=useCreateAdminSupport();const update=useUpdateAdminSupport();
  const [openForm,setOpenForm]=useState(false);const [shopId,setShopId]=useState('');const [subject,setSubject]=useState('');const [description,setDescription]=useState('');const [newPriority,setNewPriority]=useState<SupportPriority>('normal');
  const total=q.data?.[0]?.total_count??0;
  const apply=()=>{setOffset(0);setApplied(search.trim())};
  const submit=async()=>{await create.mutateAsync({shopId:shopId||null,subject:subject.trim(),description:description.trim(),priority:newPriority});setSubject('');setDescription('');setShopId('');setNewPriority('normal');setOpenForm(false)};
  return <Page title="Suporte" subtitle={total+' ticket'+(Number(total)===1?'':'s')+' registado'+(Number(total)===1?'':'s')} actions={<div className="flex gap-2"><Button size="sm" onClick={()=>setOpenForm(v=>!v)}><Plus size={14}/>Registar ticket</Button><Button variant="secondary" size="sm" onClick={()=>void q.refetch()} disabled={q.isFetching}><RefreshCw size={14} className={q.isFetching?'animate-spin':''}/>Actualizar</Button></div>}>
    {openForm&&<Panel className="mb-4" title="Novo ticket"><div className="grid md:grid-cols-2 gap-3"><label><span className="t-label text-ink-mid">Barbearia</span><select className="field w-full mt-1.5" value={shopId} onChange={e=>setShopId(e.target.value)}><option value="">Sem barbearia</option>{shops.data?.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label><span className="t-label text-ink-mid">Prioridade</span><select className="field w-full mt-1.5" value={newPriority} onChange={e=>setNewPriority(e.target.value as SupportPriority)}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label></div><label className="block mt-3"><span className="t-label text-ink-mid">Assunto</span><input className="field w-full mt-1.5" value={subject} onChange={e=>setSubject(e.target.value)} maxLength={180}/></label><label className="block mt-3"><span className="t-label text-ink-mid">Descrição</span><textarea className="field w-full mt-1.5 min-h-28" value={description} onChange={e=>setDescription(e.target.value)} maxLength={5000}/></label>{create.error&&<div className="mt-3"><ErrorState message={humanError(create.error)}/></div>}<div className="flex gap-2 mt-4"><Button onClick={()=>void submit()} loading={create.isPending} disabled={subject.trim().length<3||description.trim().length<3}>Criar ticket</Button><Button variant="secondary" onClick={()=>setOpenForm(false)}>Cancelar</Button></div></Panel>}
    <SearchToolbar><div className="relative flex-1"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-lo"/><input className="field pl-9 w-full" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')apply()}} placeholder="Assunto, descrição ou barbearia" aria-label="Pesquisar suporte"/></div><select className="field lg:w-40" value={status??''} onChange={e=>{setStatus((e.target.value||null) as SupportStatus|null);setOffset(0)}}><option value="">Todos</option><option value="open">Abertos</option><option value="in_progress">Em curso</option><option value="resolved">Resolvidos</option><option value="closed">Fechados</option></select><select className="field lg:w-36" value={priority??''} onChange={e=>{setPriority((e.target.value||null) as SupportPriority|null);setOffset(0)}}><option value="">Prioridades</option><option value="urgent">Urgente</option><option value="high">Alta</option><option value="normal">Normal</option><option value="low">Baixa</option></select><Button size="sm" onClick={apply}><Search size={14}/>Pesquisar</Button></SearchToolbar>
    {q.isLoading?<Skeleton className="h-72"/>:q.error?<ErrorState message={humanError(q.error)} onRetry={()=>void q.refetch()}/>:q.data?.length===0?<EmptyState title="Sem tickets de suporte." body="O painel está pronto para receber ocorrências reais das barbearias."/>:<div className="space-y-3">{q.data.map(t=><Panel key={t.id} className="p-4 sm:p-5"><div className="flex flex-col xl:flex-row xl:items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-ink-hi font-medium">{t.subject}</p><AdminStatus kind="support" value={t.status}/><AdminStatus kind="priority" value={t.priority}/></div><p className="t-body text-ink-mid mt-2 whitespace-pre-wrap">{t.description}</p><p className="t-label text-ink-lo mt-3">{t.shop_name??'Sem barbearia'} · criado por {t.created_by_name??'sistema'} · {fmt(t.created_at,'dd MMM yyyy, HH:mm')}</p></div><div className="w-full xl:w-80 grid grid-cols-2 gap-2"><select className="field" aria-label="Estado do ticket" value={t.status} onChange={e=>void update.mutateAsync({ticketId:t.id,status:e.target.value as SupportStatus})}><option value="open">Aberto</option><option value="in_progress">Em curso</option><option value="resolved">Resolvido</option><option value="closed">Fechado</option></select><select className="field" aria-label="Prioridade do ticket" value={t.priority} onChange={e=>void update.mutateAsync({ticketId:t.id,priority:e.target.value as SupportPriority})}><option value="urgent">Urgente</option><option value="high">Alta</option><option value="normal">Normal</option><option value="low">Baixa</option></select><select className="field col-span-2" aria-label="Responsável pelo ticket" value={t.assigned_to??''} onChange={e=>void update.mutateAsync({ticketId:t.id,assignedTo:e.target.value||null})}><option value="">Sem responsável</option>{admins.data?.filter(u=>u.is_platform_admin).map(u=><option key={u.id} value={u.id}>{u.full_name||u.email}</option>)}</select></div></div>{update.error&&<div className="mt-3"><ErrorState message={humanError(update.error)}/></div>}</Panel>)}</div>}
    {!q.isLoading&&!q.error&&<Pager offset={offset} pageSize={PAGE_SIZE} total={Number(total)} onPrev={()=>setOffset(Math.max(0,offset-PAGE_SIZE))} onNext={()=>setOffset(offset+PAGE_SIZE)}/>}
  </Page>
}